on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          always-auth: true
      - run: npm install
      # auto-bump to a new minor version
      # - run: yarn version --minor --no-git-tag-version
      - run: npm run ppare-deploy-npm
      - run: npm deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
